services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: npm run dev
  backend: # Fast Api Server
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/app:/app
    #command: uvicorn main:app --reload
    # Puts in blank shell states
    command: poetry run uvicorn app.server:app --host 0.0.0.0 --port 5000 --reload

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoAdmin
      MONGO_INITDB_ROOT_PASSWORD: m0ng0p@ssw0rd

volumes:
  mongodata:
    driver: local   
# docker-compose.yml
version: '3.7'

